### ISSUE TITLE
`onChangeValue` is not triggered when input value is selected then deleted

### ISSUE THREAD

**Issue by danilo-kvet** [leoreisdias/react-currency-mask#4]
Video demo:
https://github.com/leoreisdias/react-currency-mask/assets/69875726/fc95696a-f633-41c4-aebb-704c16394d28

Actual code:
![image](https://github.com/leoreisdias/react-currency-mask/assets/69875726/9c69a378-d4f0-4f9c-81a5-b2f1f7807780)

**Comment by dthabata** [comment]
Same here!! Tried to change states using all different ways to prevent this error, but I also don't seem to find a solution to correct this.

Feels like when I delete only the numbers slowly like @danilo-kvet demonstrates on the video demo, or selecting it all quickly — but only the numbers —, it seems to go correctly (I'm not sure it happens at all times but seems to happen in most cases), but definetly when I erase it all including “R$” like demonstrated above, the onChangeValue does not update the value for its correct one.

**Comment by leoreisdias** [comment]
Hi everyone, thanks for the feedback. I couldn't load the demo video but I will investigate locally as soon as possible in search of a good solution. Meanwhile, if you find any possible solution, feel free to comment here or open a PR. Thanks for your patience in advance.

**Comment by leoreisdias** [comment]
Hi again, issue was closed after a fix from PR opened by @eliezer-alves. Thanks again for the feedback and contribution.
