### ISSUE TITLE
Handle blur does not trigger when masked value is empty

### ISSUE THREAD

**Issue by mmbfreitas** [leoreisdias/react-currency-mask#7]
Hi, i don't know why you area validating masked value to trigger handle blur 

`if (maskedValue && onBlur) {
        onBlur(event, originalValue, maskedValue);
      }`

I think that should trigger anyway and who implements onBlur should validate values, right?

I tried to open an branch to push fix, but I have no permission

**Comment by leoreisdias** [comment]
Hi, sorry for the late answer. Indeed, you have a good point. I reviewed your PR and pushed it. Thank you for the insight. Your fix is now on version 1.3.2
